### ISSUE TITLE
Não é possivel instalar 

### ISSUE THREAD

**Issue by jvoltz** [linkapi/getokr-web#2]
Pessoal, não consigo rodar o front. Alguém pode ajudar? 

![image](https://user-images.githubusercontent.com/47332274/52233115-67574c00-28a5-11e9-89ae-61c61100b7a4.png)

**Comment by icarocleto** [comment]
@jvoltz, poderia informar qual a versão do Node/Npm vc está utilizando?

**Comment by jvoltz** [comment]
@icarocleto Olá. Eu estava testando em um Ubuntu com a versão 10.15 do node.

**Comment by icarocleto** [comment]
@jvoltz, Poderia tentar rodar novamente utilizando a versão 6.11.5 do node?

**Comment by mtkkk** [comment]
Estou com um problema semelhante, instalei a versao 6.11.5 do node e deu tudo certo... O problema é que com a versão 6.11.5 o problema ocorre com o 'getokr-api' , não reconhece o token 'async function' (que pelo que vi só está disponível no node 7.6 pra cima.

Instalei o 7.6 e o problema volta a ocorrer no getokr-web

**Comment by icarocleto** [comment]
@mtkkk Obrigado por reportar o problema, subi uma alteração tanto na API quanto no WEB para corrigir o mesmo.

Após corrigir o problema, realizei os testes utilizando a versão 8.11.1 de Node e 3.10.10 do NPM.

Poderia tentar novamente? Aguardo o feedback

**Comment by mtkkk** [comment]
Problema resolvido! Obrigado pela atenção :)
